### ISSUE TITLE
Error docker-compose up

### ISSUE THREAD

**Issue by VAVASIN** [mafuuu-dev/leads.tech-test#1]
Добрый день.
Не взлетел Ваш докер.
Скрин ошибки после команды: docker-compose up -d && docker-compose logs -f --tail=0
![image](https://user-images.githubusercontent.com/45480141/129523281-1cd58697-c30a-4eb6-a86b-cfe0450b6ef5.png)

**Comment by mafuuu-dev** [comment]
Добрый день! Какая у вас версия докера?

**Comment by VAVASIN** [comment]
![image](https://user-images.githubusercontent.com/45480141/129527384-84604338-e6a0-45c4-9721-358bf844ba2c.png)

**Comment by mafuuu-dev** [comment]
обновите докер до версии 20.10.0 или выше. alpine3.14 имеет некоторые особенности.
подробности по ссылке ниже: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2

**Comment by mafuuu-dev** [comment]
можете изменить версию alpine на 3.13, я сейчас проверил все работает (но у меня docker 20.10.7).
